[课程](https://tf.wiki/zh/basic/basic.html)

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [2]:
# 定义一个随机数（标量）
random_float = tf.random.uniform(shape=())

# 定义一个有2个元素的零向量
zero_vector = tf.zeros(shape=(2))

# 定义两个2×2的常量矩阵
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])

In [3]:
print(A.shape)
print(A.dtype)
print(A.numpy())

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [4]:
C=tf.add(A,B)

In [5]:
C

<tf.Tensor: id=12, shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [6]:
D=tf.matmul(A,B)

In [7]:
D

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

计算函数 y(x) = x^2 在 x = 3 时的导数使用`tf.GradientTape()`

In [8]:
x=tf.Variable(initial_value=3.)

In [9]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [10]:
with tf.GradientTape() as tape:
    y=tf.square(x)
y_grad=tape.gradient(y,x)
print([y,y_grad])

[<tf.Tensor: id=24, shape=(), dtype=float32, numpy=9.0>, <tf.Tensor: id=28, shape=(), dtype=float32, numpy=6.0>]


In [11]:
!ls

binder	Index.ipynb  LICENSE  models_score.ipynb  README.md  TensorFlow.ipynb


In [14]:
import numpy as np

X_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype=np.float32)
y_raw = np.array([12000, 14000, 15000, 16500, 17500], dtype=np.float32)

X = (X_raw - X_raw.min()) / (X_raw.max() - X_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

In [17]:
X

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [18]:
a,b=0,0
num_epoch=10000
learning_rate=1e-3
for e in range(num_epoch):
    y_pred=a*X+b
    grad_a, grad_b = (y_pred - y).dot(X), (y_pred - y).sum()

    # 更新参数
    a, b = a - learning_rate * grad_a, b - learning_rate * grad_b
print(a,b)

0.9763702027872221 0.057564988311377796


In [19]:
X = tf.constant(X)
y = tf.constant(y)

a = tf.Variable(initial_value=0.)
b = tf.Variable(initial_value=0.)
variables = [a, b]

num_epoch = 10000
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
for e in range(num_epoch):
    # 使用tf.GradientTape()记录损失函数的梯度信息
    with tf.GradientTape() as tape:
        y_pred = a * X + b
        loss = 0.5 * tf.reduce_sum(tf.square(y_pred - y))
    # TensorFlow自动计算损失函数关于自变量（模型参数）的梯度
    grads = tape.gradient(loss, variables)
    # TensorFlow自动根据梯度更新参数
    optimizer.apply_gradients(grads_and_vars=zip(grads, variables))

print(a, b)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.97637> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.057565063>
